HOST_NAME = "https://staging.teambit.io"

SIGNUP_PAGE_URL = HOST_NAME + "/signup"
LOGIN_PAGE_URL = HOST_NAME + "/signin"
FEEDBACK_ALL_URL = HOST_NAME + "/feedback"
FEEDBACK_TO_YOU_URL = HOST_NAME + "/feedback/to-you"
FEEDBACK_ADDED_TO_PRAISE_URL = HOST_NAME + "/feedback/praised"
FEEDBACK_VIA_SURVEYS_URL = HOST_NAME + "/feedback/surveys"
FEEDBACK_VIA_REVIEWS_URL = HOST_NAME + "/feedback/reviews"
FEEDBACK_SENT_URL = HOST_NAME + "/feedback/sent"
FEEDBACK_FLAGGED_URL = HOST_NAME + "/feedback/flagged"
REQUEST_PAGE_URL = HOST_NAME + "/requests"
REQUEST_SENT_URL = HOST_NAME + "/requests/sent"
REQUEST_RESOLVED_URL = HOST_NAME + "/requests/resolved"
SURVEY_PAGE_URL = HOST_NAME + "/surveys"
PEOPLE_PAGE_URL = HOST_NAME + "/people"
TEAMMATE_PAGE_URL = HOST_NAME + "/users/"
TEAMS_PAGE_URL = HOST_NAME + "/teams/"